import cv2
import matplotlib.pyplot as plt
import numpy as np
def interactive_edge_detection(image_path):
    image = cv2.imread(image_path)
    if image is None:
        print("Image not found.")
        return
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    while True:
        print("select an option:")
        print("1. Canny Edge Detection")
        print("2. Sobel Edge Detection")
        print("3. Laplacian Edge Detection")
        print("4. Gaussian Smoothing")
        print("5. Median Filtering")
        print("6. Exit")
        choice = input("Enter choice (1-6): ").strip()
        if choice == "1":
            lower_threshold = int(input("Enter lower threshold (0-255): "))
            upper_threshold = int(input("Enter upper threshold (0-255): "))
            edges = cv2.Canny(gray_image, lower_threshold, upper_threshold)
            plt.figure()
            plt.imshow(gray_image, cmap='gray')
            plt.title("gray image before Canny")
            plt.axis('off')
            plt.show()
            plt.figure()
            plt.imshow(edges, cmap='gray')
            plt.title("Canny Edge Detection")
            plt.axis('off')
            plt.show()
        elif choice == "2":
            Sobel_x = cv2.Sobel(gray_image, cv2.CV_64F, 1, 0, ksize=5)
            Sobel_y = cv2.Sobel(gray_image, cv2.CV_64F, 0, 1, ksize=5)
            combined_sobel = cv2.bitwise_or(Sobel_x.astype(np.uint8), Sobel_y.astype(np.uint8))
            plt.figure()
            plt.imshow(gray_image, cmap='gray')
            plt.title("gray image before Sobel")
            plt.axis('off')
            plt.show()
            plt.figure()
            plt.imshow(combined_sobel, cmap='gray')
            plt.title("gray image after Sobel Edge Detection")
            plt.axis('off')
            plt.show()
        elif choice == "3":
            Laplacian = cv2.Laplacian(gray_image, cv2.CV_64F)
            plt.figure()
            plt.imshow(gray_image, cmap='gray')
            plt.title("gray image before Laplacian")
            plt.axis('off')
            plt.show()
            plt.figure()
            plt.imshow(np.abs(Laplacian).astype(np.uint8), cmap='gray')
            plt.title("gray image after Laplacian Edge Detection")
            plt.axis('off')
            plt.show()
        elif choice == "4":
            print("Adjust kernel size for Gaussian smoothing (must be odd):")
            ksize = int(input("Enter kernel size: "))
            blured_image = cv2.GaussianBlur(image, (ksize, ksize), 0)
            plt.figure()
            plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
            plt.title("image before Gaussian Smoothing")
            plt.axis('off')
            plt.show()
            plt.figure()
            plt.imshow(cv2.cvtColor(blured_image, cv2.COLOR_BGR2RGB))
            plt.title("image after Gaussian Smoothing")
            plt.axis('off')
            plt.show()
        elif choice == "5":
            print("Adjust kernel size for median filtering (must be odd):")
            ksize = int(input("Enter kernel size: "))
            median_filtered = cv2.medianBlur(image, ksize)
            plt.figure()
            plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
            plt.title("image before Median Filtering")
            plt.axis('off')
            plt.show()
            plt.figure()
            plt.imshow(cv2.cvtColor(median_filtered, cv2.COLOR_BGR2RGB))
            plt.title("image after Median Filtering")
            plt.axis('off')
            plt.show()
        elif choice == "6":
            print("Exiting...")
            break
        else:
            print("Invalid choice.")
interactive_edge_detection("example.jpg")